In [1]:
import torch
from   torch.utils.data import DataLoader

In [2]:
t_ = torch.arange(6, dtype=torch.float32)
t_

tensor([0., 1., 2., 3., 4., 5.])

In [3]:
data_loader = DataLoader(t_)

In [5]:
for item_ in data_loader:
    print(item_)

tensor([0.])
tensor([1.])
tensor([2.])
tensor([3.])
tensor([4.])
tensor([5.])


In [6]:
data_loader = DataLoader(dataset=t_, batch_size=3, drop_last=True)

In [8]:
for i, batch in enumerate(data_loader, 1):
    print(f'pacote_{i} : {batch}')

pacote_1 : tensor([0., 1., 2.])
pacote_2 : tensor([3., 4., 5.])


In [9]:
torch.manual_seed(seed=32)

In [10]:
feature = torch.rand(size=(4, 3), dtype=torch.float32)
target  = torch.arange(4)

In [12]:
from torch.utils.data import Dataset, TensorDataset


class JointDataset(Dataset):
    def __init__(self, X, y):
        self.x = X
        self.y = y
    
    def __len__(self):
        return len(self.y)
    
    def __getitem__(self, index):
        return self.x[index], self.y[index]

In [14]:
joint_ = JointDataset(feature, target)

In [15]:
for example in joint_:
    print(example)

(tensor([0.8757, 0.2721, 0.4141]), tensor(0))
(tensor([0.7857, 0.1130, 0.5793]), tensor(1))
(tensor([0.6481, 0.0229, 0.5874]), tensor(2))
(tensor([0.3254, 0.9485, 0.5219]), tensor(3))


In [16]:
for example_ in TensorDataset(feature, target):
    print(example_)

(tensor([0.8757, 0.2721, 0.4141]), tensor(0))
(tensor([0.7857, 0.1130, 0.5793]), tensor(1))
(tensor([0.6481, 0.0229, 0.5874]), tensor(2))
(tensor([0.3254, 0.9485, 0.5219]), tensor(3))
