In [1]:
import torch
import numpy as np

In [2]:
a = [1, 2, 3]
b = np.array([4, 5, 6], dtype=np.int32)

In [3]:
torch.tensor(a)

tensor([1, 2, 3])

In [4]:
torch.from_numpy(b)

tensor([4, 5, 6], dtype=torch.int32)

In [6]:
torch.ones(size=(2, 3))

tensor([[1., 1., 1.],
        [1., 1., 1.]])